hwi_oauth:
    resource_owners:
        auth0:
            type:                auth0
            client_id:           '%env(AUTH0_CLIENT_ID)%'
            client_secret:       '%env(AUTH0_CLIENT_SECRET)%'
            base_url:            'https://%env(AUTH0_DOMAIN)%'
            scope:               'openid profile email'
